### ISSUE TITLE
Low contrast on command name in palette

### ISSUE THREAD

**Issue by willrowe** [meetio-theme/sublime-meetio-theme#57] opened 2021-09-23 11:57 UTC
**Describe the bug**
When running a command with input in the command palette, both the foreground and background color are dark. This is happening with the Sublime Merge theme as well.

**To Reproduce**
1. Set the theme to `Meetio Theme High Contrast.sublime-theme`.
2. Set the color scheme to `Meetio Deepocean`.
3. Open the command palette
4. Select `Arithmetic`.

**Expected behavior**
Either the background or foreground should be a contrasting light color to make it easier to read.

**Screenshots**
![Screen_Shot_2021-09-03_at_11 03 03_AM](https://user-images.githubusercontent.com/7152423/134501601-84610c35-72f8-47fa-a3ec-1eec14d717eb.png)

**Comment by mauroreisvieira** [comment] 2021-09-24 08:55
Hey @willrowe thanks for the report, will be fixed ASAP:

**Comment by willrowe** [comment] 2021-10-14 14:38
@mauroreisvieira any update on this?

**Comment by TerminalFi** [comment] 2021-10-14 15:23
Hey! Let me look into this

**Comment by TerminalFi** [comment] 2021-10-14 15:45
@willrowe @mauroreisvieira 

The problem is that our Color Schemes are defining these three properties

```
popup_css
phantom_css
sheet_css
```

Sublime Text has a bug that if these are defined, they override all values. It should combine them with the default values but it doesn't. This is causing the bug that is listed in this ticket as well as a bug for popups and html content.

@mauroreisvieira we need to remove these three settings until Sublime Devs fix it.

https://github.com/sublimehq/sublime_text/issues/3651

**Comment by mauroreisvieira** [comment] 2021-10-14 16:00
Hey, @TheSecEng thanks a lot for your help. I will fix that.

**Closed as completed** 2021-10-14 16:03 UTC
Labels: bug

**Comment by willrowe** [comment] 2021-10-18 13:19
Thanks! That fixed it.
